name: Build, Test & Deploy React application to github pages
on:
  push:
    branches: [ main ]
jobs:
  build-test-deploy:
    name: Build, Test & Deploy React app
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Test
      run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'Robert Skaar'
        git config --global user.email 'rhskaar@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        npm run deploy
